### ISSUE TITLE
InResponseTo must match the Request

### ISSUE THREAD

**Issue by nicolabeghin** [lscorcia/keycloak-spid-provider#18]
# Issue overview
As part of the 100+ checks performed by [spid-saml-check](https://github.com/italia/spid-saml-check) in order to pass SPID validation, `Assertion.Subject.SubjectConfirmationData.InResponseTo` 
![image](https://user-images.githubusercontent.com/2743637/111533250-dbdc6480-8766-11eb-82b9-4469d4e6e1c0.png)

must match the SAML request ID
![image](https://user-images.githubusercontent.com/2743637/111533561-34abfd00-8767-11eb-8049-a62a3618c0ac.png)

If not available or mismatching, 3 different mandatory tests fails.
![image](https://user-images.githubusercontent.com/2743637/111533731-69b84f80-8767-11eb-8b3a-fbfef90f0f1b.png)

# Proposal
This can be checked in `SpidSAMLEndpoint.handleLoginResponse`, problem is, I cannot find any way to retrieve the original request data! @lscorcia any hint on this? 
`!assertion.getSubject().getConfirmation().stream().findFirst().get().getSubjectConfirmationData().getInResponseTo()`

**Comment by GermanoGiudici** [comment]
@nicolabeghin I guess you have to debug the request flow, starting from the SpidIdentityProvider class, you have to check if the request is saved somewhere, If not you have to create some store where to put the request, accessible also by the endpoint (be aware of clustering issue).

**Comment by nicolabeghin** [comment]
Thanks, I spent some hours debugging in SpidSAMLEndpoint but couldn't find any place where the request is stored, so will try to dig more. I found out keycloak checks InResponseTo already when SP initiated so hope to find a way to reuse standard code because otherwise it would mean a lot of work is required in Keycloak foundation to get it working with Spid.

**Comment by nicolabeghin** [comment]
[InResponseTo check](https://github.com/keycloak/keycloak/blob/master/saml-core/src/main/java/org/keycloak/saml/common/DefaultPicketLinkLogger.java#L1462) in existing Keycloak sources

**Comment by nicolabeghin** [comment]
tentative (not sure): in `SpidIdentityProvider.performLogin` store request Assertion ID in order to be able to retrieve it for comparison in `Response`:

`request.getAuthenticationSession().setClientNote("requestID", authnRequest.getID());`

**Comment by nicolabeghin** [comment]
Submitted PR #22
