### ISSUE TITLE
spid-sp-metadata endpoint

### ISSUE THREAD

**Issue by GermanoGiudici** [lscorcia/keycloak-spid-provider#2]
Ciao Luca, stiamo cercando di integrare il plugin per utilizzare SPID nel nostro prodotto Entando (https://www.entando.com/).
Ho visto dal codice che esiste un endpoint spid-sp-metadata (SpidSpMetadataResourceProvider) che mi sembra non documentato.
Mi è sfuggita? Magari è una nuova feature su cui stai lavorando? Grazie mille

**Comment by lscorcia** [comment]
Ciao, hai perfettamente ragione, non ho ancora documentato l'endpoint, ma è funzionante. E' pubblicato all'indirizzo `https://login.domain.com/auth/realms/<nome realm>/spid-sp-metadata` e produce un descrittore SAML unico che comprende tutti gli IdP di tipo SPID.

Non l'ho ancora documentato perché il metadato generato non è compliant con la pubblicazione dell'avviso SPID n. 29v3, che ha introdotto nuovi attributi descrittivi che non ho ancora avuto il tempo di inserire. Ho comunque intenzione di farlo appena possibile, almeno per quanto previsto per gli SP pubblici.

**Comment by lscorcia** [comment]
Funzionalità completata nella versione 1.0.7 e documentata nel wiki ;)
