### ISSUE TITLE
Log request e response SAML

### ISSUE THREAD

**Issue by gverdesca** [lscorcia/keycloak-spid-provider#21]
All'interno del manuale operativo SPID è prevista la necessità di loggare tutte le richieste di autenticazione. La gestione di questa funzionalità è stata prevista in questo progetto?

**Comment by lscorcia** [comment]
Non ho verificato, ma mi pare che sia possibile loggare le richieste/risposte settando opportunamente i livelli di logging di Keycloak (l'ho fatto all'inizio del progetto, quando mi serviva fare un po' più di prove). Non ricordo esattamente cosa mettere nel file standalone.xml, ma non era difficile - lo cerco di nuovo e ti aggiorno.
