### ISSUE TITLE
Errore di validazione

### ISSUE THREAD

**Issue by gverdesca** [lscorcia/keycloak-spid-provider#6]
Ciao Luca,
utilizzando la versione 12.0.3 di keycloak e seguendo le indicazioni del Wiki ho provato ad effettuare un test di autenticazione SPID riscontrato però il seguente errore di validazione:

AuthnRequest/RequestedAuthnContext | required key not provided

Sapresti dirmi, per favore, da cosa possa dipendere questo errore?

Grazie

Giovanni

**Comment by lscorcia** [comment]
Ciao!
Ti sei ricordato di inserire il livello SPID nella sezione apposita della configurazione dell'Identity Provider?

![immagine](https://user-images.githubusercontent.com/16761934/109304218-39eaeb80-783c-11eb-8e42-2f2bc3e3a6d6.png)

**Comment by francucchi** [comment]
Ciao,
sto avendo lo stesso problema riportato sopra e nel mio caso non sembra essere dovuto ad una semplice dimenticanza.
Ho notato che in alcuni deployment di keycloak (ad esempio tramite le charts di codecentric su kubernetes per sfruttare le replicazioni) la parte dell'authncontext non viene correttamente riconosciuta e inoltre non è sembra possibile salvare una ClassRefs sebbene il salvataggio delle configurazioni non generi errore.
In pratica, quando vengono poi scambiati i metadati con l'ambiente di test di SPID appare effettivamente l'errore di cui sopra.
Allego screenshot del problema.

Grazie
Franco

![Keycloak_spid_issue](https://user-images.githubusercontent.com/30141809/109614547-1329ff00-7b33-11eb-80ed-b7c00fb605cb.PNG)

**Comment by lscorcia** [comment]
Buongiorno Francesco,
c'è sicuramente qualcosa che non va nel caricamento del plugin, vedo che le risorse non vengono caricate (dovrebbe mostrarti dei testi anziché le chiavi di traduzione. Non conosco Kubernetes, e non ho idea di cosa cambi nel caso di pubblicazione sotto questo tipo di container, però intanto, posso chiederti di verificare che versione di Keycloak avete in esecuzione? Le versioni inferiori alla 11.x o inferiori non supportano il plugin. Altra cosa... visto che sembra essere un problema di caricamento del plugin, avete già provato a riavviare il container?

**Comment by francucchi** [comment]
Grazie Luca,
ho fatto un po' di troubleshooting e purtroppo c'era un problema nel file properties dei temi di base che non presentava tutti i campi.
Ho risolto importando nuovamente i temi base.

Grazie
Franco

**Comment by lscorcia** [comment]
Non ho capito, è rientrato solo il problema delle lingue o è rientrata anche l'anomalia inizialmente segnalata sul mancato salvataggio dei classrefs?

**Comment by fcdevitel** [comment]
Grazie per l'interessamento, nel mio caso successivamente è rientrata anche l'anomalia del mancato salvataggio ma stranamente è stato necessario che un altro utente si loggasse con account amministrativo per aggiungere la ClassRefs in quanto dal mio browser non vi era modo cliccando sul + di aggiungere nulla.
Comunque problema risolto.

Grazie ancora
Franco

**Comment by lscorcia** [comment]
Issue chiusa per risoluzione autonoma problematiche.
