### ISSUE TITLE
The AuthnRequest must validate against XSD and must have a valid signature stderr

### ISSUE THREAD

**Issue by matteo2411** [lscorcia/keycloak-spid-provider#8]
Facendo una prova di request con lo SPID Validator la validazione va in errore perchè la firma sulla request non è valida. Anche verificandola con tool esterni mi da errori di firma. 
Questo è l'errore che ottengo:

The AuthnRequest must validate against XSD and must have a valid signature stderr: ./script/check-request-xsd-and-signature.sh: line 17: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 19: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 22: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 25: $'\r': command not found stderr: cat: './data/https___172_23_208_1_8443_auth_realms_libretto_formativo'$'\r''/SAMLRequest.authn'$'\r''.request.txt': No such file or directory stderr: ./script/check-request-xsd-and-signature.sh: line 70: syntax error near unexpected token `elif' stderr: ./script/check-request-xsd-and-signature.sh: line 70: ` elif [ "${CTX}" == "logout" ]; then '
--

Questa la request generata da keycloak:

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" AssertionConsumerServiceURL="https://localhost:8443/auth/realms/libretto-formativo/broker/spid-validatore/endpoint" AttributeConsumingServiceIndex="1" Destination="http://localhost:8080/samlsso" ForceAuthn="true" ID="ID_4637e04b-0c84-4620-b90a-d678d308ef4f" IssueInstant="2021-03-03T12:11:24.268Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
    <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://172.23.208.1:8443/auth/realms/libretto-formativo">
        https://172.23.208.1:8443/auth/realms/libretto-formativo
    </saml:Issuer>
    <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
        <dsig:SignedInfo>
            <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <dsig:Reference URI="#ID_4637e04b-0c84-4620-b90a-d678d308ef4f">
                <dsig:Transforms>
                    <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </dsig:Transforms>
                <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <dsig:DigestValue>
                    dDtQlncZlx4gzOA/zFy4RyEkthCfDD9FG01yi7sETGQ=
                </dsig:DigestValue>
            </dsig:Reference>
        </dsig:SignedInfo>
        <dsig:SignatureValue>
            M69SnrfUH6bQG7sQ9Wb3KK32vM9/aezw2fKVmOsUjYKp1oZNEcIOs10X86TvOz/Nwr8RwbIOJKAZeDAoghl/4wMrXUKlM6NSqzRf09jgjiNMqDN/DpwXgoeXwGO4MA+Hp+5cfuYuvIt5F51+mJZ7wNLVMe+wsjqpi+g2hEPqHct/Y3pjl16oZAjFureEgOuLFg/QzV4TYtc5LlHTkVo9JwWC0T8YsT0Srvv9CvUCEbXUcKv0B2Z7ZEEYi73hxbNNg33h0OssSJ6Nq6Loh4HW5dAxxiPKwH9d3901/EpBLHc3wA9g7WymH4B/M8dKrq1zEdfVyHOMWXiH4aCFepmHeQ==
        </dsig:SignatureValue>
        <dsig:KeyInfo>
            <dsig:X509Data>
                <dsig:X509Certificate>
                    MIICszCCAZsCBgF39/9GIzANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDDBJsaWJyZXR0by1mb3JtYXRpdm8wHhcNMjEwMzAzMTIwODU3WhcNMzEwMzAzMTIxMDM3WjAdMRswGQYDVQQDDBJsaWJyZXR0by1mb3JtYXRpdm8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMUHAy6S4wPJSfAYGqIck1G+MvPLEisUq0Tlqvjx4nXwwjmAMpIAJ+Nss8a+LoaAIXrly7Wi6jCzWkNOEKOXi0cqWWGmtGjYePoerNisxI+srtZivuJ7rHoxBesCgSnaSlDFAE5D/HzNuE525VQbmcdbh0qzn6ETMran48ngdQFNlxBBLFeeVO47uxN64akkT8CBlVC0P3FBjE0zfpvTLlz2O1dIfcZ+7d+pUatJQ/D2R54EO0+cN/KvbEDPbjXEAIDdJApGXXxZ44ZaE7Sv2PTjb8HswBwjePuWbJNeeo0kJso9nX84OUboakJLlS3yN5t+dg7Ef0BCCHYnZpBBstAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEaWueA7RH2xXonfJynBHqXHvmukNvyIAz/HjfHezGS5+FBrLeo+GuELNT+E1MFfJ0c41i2Eqc792iLLsf5I9JVXPkkpujrBJvxu/lEnXUFHwyNx8TTcB3Gdz0WAUfS5qEYNXl5K3mHBy3TVD/qhYbF1ei60nk8vBk+OSvHkIqcIGMk9HO2OLL7ayuVGo4R0qCGZQhCbEldQzVKat0h5CtBA+Xxg1VSxmuNgf4shmInT6bRVKdFn7Ou37QGg2K9s8m1eHEt7xf28N+jrAVD4F+BQF0gSmu2xXQ/xUT78cWJfzvHqCTPmiyWWky8P6/NsePX1a+PGC4/LYUgbBAb0U4A=
                </dsig:X509Certificate>
            </dsig:X509Data>
            <dsig:KeyValue>
                <dsig:RSAKeyValue>
                    <dsig:Modulus>
                        zFBwMukuMDyUnwGBqiHJNRvjLzyxIrFKtE5ar48eJ18MI5gDKSACfjbLPGvi6GgCF65cu1ouows1pDThCjl4tHKllhprRo2Hj6HqzYrMSPrK7WYr7ie6x6MQXrAoEp2kpQxQBOQ/x8zbhOduVUG5nHW4dKs5+hEzK2p+PJ4HUBTZcQQSxXnlTuO7sTeuGpJE/AgZVQtD9xQYxNM36b0y5c9jtXSH3Gfu3fqVGrSUPw9keeBDtPnDfyr2xAz241xACA3SQKRl18WeOGWhO0r9j042/B7MAcI3j7lmyTXnqNJCbKPZ1/ODlG6GpCS5Ut8jebfnYOxH9AQgh2J2aQQbLQ==
                    </dsig:Modulus>
                    <dsig:Exponent>
                        AQAB
                    </dsig:Exponent>
                </dsig:RSAKeyValue>
            </dsig:KeyValue>
        </dsig:KeyInfo>
    </dsig:Signature>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="https://172.23.208.1:8443/auth/realms/libretto-formativo"/>
    <samlp:RequestedAuthnContext Comparison="minimum">
        <saml:AuthnContextClassRef>
            https://www.spid.gov.it/SpidL2
        </saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>

```

**Comment by lscorcia** [comment]
Ciao, il messaggio XML è firmato correttamente, ho eseguito la validazione con https://tools.chilkat.io/xmlDsigVerify.cshtml e risulta valida.
Quale SPID validator stai utilizzando?

**Comment by matteo2411** [comment]
Ce n'è piu di uno? Sto usando spid saml check

**Comment by lscorcia** [comment]
Si ce ne sono un altro paio, ma spid-saml-check è quello giusto... però non ho mai visto un errore simile. Sembra più un errore interno del validatore che qualcosa di dovuto all'asserzione (syntax error nello shell script). Forse colpa della piattaforma? Sei su linux? Mac?

**Comment by matteo2411** [comment]
La macchina Host è Windows... Poi il tutto gira su Docker ovviamente

**Comment by lscorcia** [comment]
Sempre più curioso. Io uso host linux, però anche io con il docker , e quindi non dovremmo avere differenze in questo senso.

Ho trovato questa issue sul repo di spid-saml-check che sembra delineare lo stesso errore all'interno del validatore stesso, senza riferimenti a Keycloak o a questo plugin: https://github.com/italia/spid-saml-check/issues/111 . 
Stranamente sul validatore che ho qui (versione latest presa da docker hub 9 giorni fa) - e sul sistema SPID di produzione - non riesco a riprodurre il problema. Può essere che la tua immagine docker sia una versione precedente?

**Comment by matteo2411** [comment]
Si potrei avere una versione piu vecchia. Domani mi aggiorno all'ultima disponibile e rieseguo la prova. Grazie mille

**Comment by matteo2411** [comment]
Mi sono aggiornato all'ultima versione, ma forse lo ero già, comunque ho lo stesso errore di ieri. Se provo a verificare la firma con https://tools.chilkat.io/xmlDsigVerify.cshtml ho questo risultato

![image](https://user-images.githubusercontent.com/12057020/109941151-24117680-7cd3-11eb-9957-ec490f7b8a50.png)

**Comment by lscorcia** [comment]
L'indentazione del file XML rende la firma non valida; purtroppo gli spazi sono significativi per XML Signature. Se rimuovi tutti gli spazi in eccesso dall'XML la firma viene superata:

![immagine](https://user-images.githubusercontent.com/16761934/109979050-c2670180-7cfe-11eb-9775-8252ab089a86.png)

Il plugin dovrebbe generare un documento senza spazi.

**Comment by matteo2411** [comment]
Ok allora il motivo è sicuramente quello, a questo punto la firma è valida ma c'è qualcosa di strano nell'ultima versione di spid-saml-check
